config/routes.rb
Rails.application.routes.draw do
  resources :requisitions
  resources :fines
  resources :equipment
  resources :equip_types
  resources :students
  resources :subjects
  resources :professors
  resources :schools
  resources :classrooms
  resources :responsibles
  resources :secretaries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
    has_and_belongs_to_many :subjects
end

app/models/equip_type.rb
class EquipType < ApplicationRecord
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :secretary
  belongs_to :equip_type
end

app/models/fine.rb
class Fine < ApplicationRecord
  belongs_to :secretary
  belongs_to :responsible
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :school
end

app/models/requisition.rb
class Requisition < ApplicationRecord
  belongs_to :responsible
  belongs_to :equipment
end

app/models/responsible.rb
class Responsible < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :secretary
end

app/models/secretary.rb
class Secretary < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :classroom
  belongs_to :responsible
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :professor
  has_and_belongs_to_many :classrooms
end

app/controllers/responsibles_controller.rb
class ResponsiblesController < ApplicationController
  before_action :set_responsible, only: [:show, :edit, :update, :destroy]

  # GET /responsibles
  # GET /responsibles.json
  def index
    @responsibles = Responsible.all
  end

  # GET /responsibles/1
  # GET /responsibles/1.json
  def show
  end

  # GET /responsibles/new
  def new
    @responsible = Responsible.new
  end

  # GET /responsibles/1/edit
  def edit
  end

  # POST /responsibles
  # POST /responsibles.json
  def create
    @responsible = Responsible.new(responsible_params)

    respond_to do |format|
      if @responsible.save
        format.html { redirect_to @responsible, notice: 'Responsible was successfully created.' }
        format.json { render :show, status: :created, location: @responsible }
      else
        format.html { render :new }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responsibles/1
  # PATCH/PUT /responsibles/1.json
  def update
    respond_to do |format|
      if @responsible.update(responsible_params)
        format.html { redirect_to @responsible, notice: 'Responsible was successfully updated.' }
        format.json { render :show, status: :ok, location: @responsible }
      else
        format.html { render :edit }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsibles/1
  # DELETE /responsibles/1.json
  def destroy
    @responsible.destroy
    respond_to do |format|
      format.html { redirect_to responsibles_url, notice: 'Responsible was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_responsible
      @responsible = Responsible.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def responsible_params
      params.require(:responsible).permit(:cpfResp, :addressResp, :nameResp, :income)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/equip_types_helper.rb
module EquipTypesHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/responsibles/_form.html.erb
<%= form_with(model: responsible, local: true) do |form| %>
  <% if responsible.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(responsible.errors.count, "error") %> prohibited this responsible from being saved:</h2>

      <ul>
        <% responsible.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cpfResp %>
    <%= form.text_field :cpfResp %>
  </div>

  <div class="field">
    <%= form.label :addressResp %>
    <%= form.text_field :addressResp %>
  </div>

  <div class="field">
    <%= form.label :nameResp %>
    <%= form.text_field :nameResp %>
  </div>

  <div class="field">
    <%= form.label :income %>
    <%= form.text_field :income %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/responsibles/edit.html.erb
<h1>Editing Responsible</h1>

<%= render 'form', responsible: @responsible %>

<%= link_to 'Show', @responsible %> |
<%= link_to 'Back', responsibles_path %>

app/views/responsibles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Responsibles</h1>

<table>
  <thead>
    <tr>
      <th>Cpfresp</th>
      <th>Addressresp</th>
      <th>Nameresp</th>
      <th>Income</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responsibles.each do |responsible| %>
      <tr>
        <td><%= responsible.cpfResp %></td>
        <td><%= responsible.addressResp %></td>
        <td><%= responsible.nameResp %></td>
        <td><%= responsible.income %></td>
        <td><%= link_to 'Show', responsible %></td>
        <td><%= link_to 'Edit', edit_responsible_path(responsible) %></td>
        <td><%= link_to 'Destroy', responsible, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Responsible', new_responsible_path %>

app/views/responsibles/new.html.erb
<h1>New Responsible</h1>

<%= render 'form', responsible: @responsible %>

<%= link_to 'Back', responsibles_path %>

app/views/responsibles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cpfresp:</strong>
  <%= @responsible.cpfResp %>
</p>

<p>
  <strong>Addressresp:</strong>
  <%= @responsible.addressResp %>
</p>

<p>
  <strong>Nameresp:</strong>
  <%= @responsible.nameResp %>
</p>

<p>
  <strong>Income:</strong>
  <%= @responsible.income %>
</p>

<%= link_to 'Edit', edit_responsible_path(@responsible) %> |
<%= link_to 'Back', responsibles_path %>