config/routes.rb
Rails.application.routes.draw do
  resources :requisitions
  resources :fines
  resources :equipment
  resources :equip_types
  resources :students
  resources :subjects
  resources :professors
  resources :schools
  resources :classrooms
  resources :responsibles
  resources :secretaries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
    has_and_belongs_to_many :subjects
end

app/models/equip_type.rb
class EquipType < ApplicationRecord
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :secretary
  belongs_to :equip_type
end

app/models/fine.rb
class Fine < ApplicationRecord
  belongs_to :secretary
  belongs_to :responsible
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :school
end

app/models/requisition.rb
class Requisition < ApplicationRecord
  belongs_to :responsible
  belongs_to :equipment
end

app/models/responsible.rb
class Responsible < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :secretary
end

app/models/secretary.rb
class Secretary < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :classroom
  belongs_to :responsible
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :professor
  has_and_belongs_to_many :classrooms
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:nameSubject, :professor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/equip_types_helper.rb
module EquipTypesHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/secretaries_helper.rb
module SecretariesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nameSubject %>
    <%= form.text_field :nameSubject %>
  </div>

  <div class="field">
    <%= form.label :professor_id %>
    <%= form.text_field :professor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Namesubject</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.nameSubject %></td>
        <td><%= subject.professor_id %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Namesubject:</strong>
  <%= @subject.nameSubject %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @subject.professor_id %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>