config/routes.rb
Rails.application.routes.draw do
  resources :requisitions
  resources :fines
  resources :equipment
  resources :equip_types
  resources :students
  resources :subjects
  resources :professors
  resources :schools
  resources :classrooms
  resources :responsibles
  resources :secretaries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
    has_and_belongs_to_many :subjects
end

app/models/equip_type.rb
class EquipType < ApplicationRecord
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :secretary
  belongs_to :equip_type
end

app/models/fine.rb
class Fine < ApplicationRecord
  belongs_to :secretary
  belongs_to :responsible
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :school
end

app/models/requisition.rb
class Requisition < ApplicationRecord
  belongs_to :responsible
  belongs_to :equipment
end

app/models/responsible.rb
class Responsible < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :secretary
end

app/models/secretary.rb
class Secretary < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :classroom
  belongs_to :responsible
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :professor
  has_and_belongs_to_many :classrooms
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def school_params
      params.require(:school).permit(:addressSchool, :nameSchool, :director, :secretary_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/equip_types_helper.rb
module EquipTypesHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/secretaries_helper.rb
module SecretariesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% school.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :addressSchool %>
    <%= form.text_field :addressSchool %>
  </div>

  <div class="field">
    <%= form.label :nameSchool %>
    <%= form.text_field :nameSchool %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div class="field">
    <%= form.label :secretary_id %>
    <%= form.text_field :secretary_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schools</h1>

<table>
  <thead>
    <tr>
      <th>Addressschool</th>
      <th>Nameschool</th>
      <th>Director</th>
      <th>Secretary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.addressSchool %></td>
        <td><%= school.nameSchool %></td>
        <td><%= school.director %></td>
        <td><%= school.secretary_id %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Addressschool:</strong>
  <%= @school.addressSchool %>
</p>

<p>
  <strong>Nameschool:</strong>
  <%= @school.nameSchool %>
</p>

<p>
  <strong>Director:</strong>
  <%= @school.director %>
</p>

<p>
  <strong>Secretary:</strong>
  <%= @school.secretary_id %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>