config/routes.rb
Rails.application.routes.draw do
  resources :requisitions
  resources :fines
  resources :equipment
  resources :equip_types
  resources :students
  resources :subjects
  resources :professors
  resources :schools
  resources :classrooms
  resources :responsibles
  resources :secretaries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
    has_and_belongs_to_many :subjects
end

app/models/equip_type.rb
class EquipType < ApplicationRecord
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :secretary
  belongs_to :equip_type
end

app/models/fine.rb
class Fine < ApplicationRecord
  belongs_to :secretary
  belongs_to :responsible
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :school
end

app/models/requisition.rb
class Requisition < ApplicationRecord
  belongs_to :responsible
  belongs_to :equipment
end

app/models/responsible.rb
class Responsible < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :secretary
end

app/models/secretary.rb
class Secretary < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :classroom
  belongs_to :responsible
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :professor
  has_and_belongs_to_many :classrooms
end

app/controllers/secretaries_controller.rb
class SecretariesController < ApplicationController
  before_action :set_secretary, only: [:show, :edit, :update, :destroy]

  # GET /secretaries
  # GET /secretaries.json
  def index
    @secretaries = Secretary.all
  end

  # GET /secretaries/1
  # GET /secretaries/1.json
  def show
  end

  # GET /secretaries/new
  def new
    @secretary = Secretary.new
  end

  # GET /secretaries/1/edit
  def edit
  end

  # POST /secretaries
  # POST /secretaries.json
  def create
    @secretary = Secretary.new(secretary_params)

    respond_to do |format|
      if @secretary.save
        format.html { redirect_to @secretary, notice: 'Secretary was successfully created.' }
        format.json { render :show, status: :created, location: @secretary }
      else
        format.html { render :new }
        format.json { render json: @secretary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secretaries/1
  # PATCH/PUT /secretaries/1.json
  def update
    respond_to do |format|
      if @secretary.update(secretary_params)
        format.html { redirect_to @secretary, notice: 'Secretary was successfully updated.' }
        format.json { render :show, status: :ok, location: @secretary }
      else
        format.html { render :edit }
        format.json { render json: @secretary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secretaries/1
  # DELETE /secretaries/1.json
  def destroy
    @secretary.destroy
    respond_to do |format|
      format.html { redirect_to secretaries_url, notice: 'Secretary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secretary
      @secretary = Secretary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def secretary_params
      params.require(:secretary).permit(:state, :coordinator)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/equip_types_helper.rb
module EquipTypesHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/secretaries_helper.rb
module SecretariesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/secretaries/_form.html.erb
<%= form_with(model: secretary, local: true) do |form| %>
  <% if secretary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(secretary.errors.count, "error") %> prohibited this secretary from being saved:</h2>

      <ul>
        <% secretary.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :coordinator %>
    <%= form.text_field :coordinator %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/secretaries/edit.html.erb
<h1>Editing Secretary</h1>

<%= render 'form', secretary: @secretary %>

<%= link_to 'Show', @secretary %> |
<%= link_to 'Back', secretaries_path %>

app/views/secretaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Secretaries</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Coordinator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @secretaries.each do |secretary| %>
      <tr>
        <td><%= secretary.state %></td>
        <td><%= secretary.coordinator %></td>
        <td><%= link_to 'Show', secretary %></td>
        <td><%= link_to 'Edit', edit_secretary_path(secretary) %></td>
        <td><%= link_to 'Destroy', secretary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Secretary', new_secretary_path %>

app/views/secretaries/new.html.erb
<h1>New Secretary</h1>

<%= render 'form', secretary: @secretary %>

<%= link_to 'Back', secretaries_path %>

app/views/secretaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @secretary.state %>
</p>

<p>
  <strong>Coordinator:</strong>
  <%= @secretary.coordinator %>
</p>

<%= link_to 'Edit', edit_secretary_path(@secretary) %> |
<%= link_to 'Back', secretaries_path %>